###
GET http://localhost:3333/cursoextensao HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3333/disciplina HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3333/empregoPublico HTTP/1.1
Content-Type: application/json

###
GET http://localhost:3333/titulacao HTTP/1.1
Content-Type: application/json
###
GET http://localhost:3333/regime HTTP/1.1
Content-Type: application/json

###
// Insert 1 
POST http://localhost:3333/cursoextensao HTTP/1.1
Content-Type: application/json

{
  "nome_extensao": "ADS",
  "tipo_extensao": "Profissionalizante",
  "status": true
}
###

POST http://localhost:3333/disciplina HTTP/1.1
Content-Type: application/json

{
"nome_disciplina": "ADS",
"descricao_disciplina": "gdgggdfgdf",
"carga_horaria": 80,
"objetivo_disciplina": "gdggdgd",
"ementa_disciplina": "gdffgfgfd",
"refenciaBasica_disciplina": "dgdgfd",
"refenciaComplementar_disciplina": "gdgfd",
"codSiga_disciplina": "gdffgdg"
}

###

POST http://localhost:3333/empregoPublico HTTP/1.1
Content-Type: application/json

{
  "cargo_publico": "Deputado",
  "situacao": true
}

###

POST http://localhost:3333/regime HTTP/1.1
Content-Type: application/json

{
  "tipo_regime": "Temporario"
}

###

POST http://localhost:3333/tipocontrato HTTP/1.1
Content-Type: application/json

{
  "tipo_contrato": "temporario"
}

###

//Insert 2
POST http://localhost:3333/cursoextensao HTTP/1.1
Content-Type: application/json

{
  "nome_extensao": "Arduino",
  "tipo_extensao": "Extra-curricular",
  "status": false
}


###
PUT  http://localhost:3333/cursoextensao/4 HTTP/1.1
Content-Type: application/json

{
  "nome_extensao": "Python"
}

###
DELETE  http://localhost:3333/cursoextensao/2 HTTP/1.1
Content-Type: application/json

