###
GET http://localhost:3333/cursos HTTP/1.1
Content-Type: application/json

###
// Insert 1
POST http://localhost:3333/cursos HTTP/1.1
Content-Type: application/json

{
  "nome_curso": "ADS",
  "descricao_curso": "Profissionalizante",
  "duracao_curso": 450,
  "situacao_curso": true,
  "cod_mec": "324545"
}


###

//Insert 2
POST http://localhost:3333/cursoextensao HTTP/1.1
Content-Type: application/json

{
  "nome_extensao": "Arduino",
  "tipo_extensao": "Extra-curricular",
  "status": false
}


###
PUT  http://localhost:3333/cursos/4 HTTP/1.1
Content-Type: application/json

{
  "nome_curso": "Python"
}

###
DELETE  http://localhost:3333/cursos/4 HTTP/1.1
Content-Type: application/json

